### ISSUE TITLE
Background Location

### ISSUE THREAD

**Issue by dentep** [IamIsPra/Sheriff#1]
Thank you for such an easy way to request runtime permissions ,but I was wondering about the location permissions. You don't have all COARSE, FINE and BACKGROUND _LOCATION. It seems like you combined "coarse" and "fine" into one. However background location request is not popping up when I request with **askFor(SheriffPermission.LOCATION)**

Am I missing something or this permissions will be added later?

**Comment by IamIsPra** [comment]
Sorry @dentep,
I am the one who missed something 😔 I added COARSE LOCATION and released version **Sheriff 1.0.1**. Now you can request coarse location permission with **askFor(SheriffPermission.COARSE_LOCATION)** and fine location permission with **askFor(SheriffPermission.FINE_LOCATION)**. Sorry for the inconvenience.
